# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeuser',
            name='nickname',
            field=models.CharField(default=0, max_length=24),
            preserve_default=False,
        ),
    ]
