# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20161014_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
